### ISSUE TITLE
Marketplace Flow -- ABI Mismatch Error

### ISSUE THREAD

**Issue by tmk1221** [oceanprotocol/ocean.py#382]
**Describe the bug**
Following through the marketplace flow in Ocean.py

I successfully startup barge and run Ocean market service.

The error occurs during "2. Alice publishes data asset".

The first error occurs after "data_token = ocean.create_data_token()". 

Something about "ABI Mismatch".

The second error I cannot continue past. It's when I run:

'''python
asset = ocean.assets.create(
  metadata,
  alice_wallet,
  service_descriptors=[download_service],
  data_token_address=token_address)
'''

The console halts, so after a minute, I press "ctrl + c" to terminate command, and receive multiple traceback errors (please see terminal output below).

Perhaps the first error is related to the second?

**To Reproduce**
[Terminal.txt](https://github.com/oceanprotocol/ocean.py/files/6826576/Terminal.txt)

**Comment by DMats** [comment]
The Mismatched ABI warnings are benign and can safely be ignored. Nonetheless we fixed them in https://github.com/oceanprotocol/ocean.py/pull/369 which will be included in the next release.

For the second error, I'd recommend waiting longer before killing it.  In times of high congestion, I've seen that command take 15 minutes.

**Comment by tmk1221** [comment]
@DMats - understood on Mismatched ABI.

I'm using Barge, so I expected there to be no congestion, therefore little latency.

I've now left the command running for an error, and it's still hanging. Perhaps it's a problem with Barge?

I see that I get a logging error in Barge output, roughly every 30 minutes. See below:
________________________

aquarius_1         | --- Logging error ---
aquarius_1         | Traceback (most recent call last):
aquarius_1         |   File "/usr/lib/python3.8/logging/__init__.py", line 1085, in emit
aquarius_1         |     self.flush()
aquarius_1         |   File "/usr/lib/python3.8/logging/__init__.py", line 1065, in flush
aquarius_1         |     self.stream.flush()
aquarius_1         | RuntimeError: reentrant call inside <_io.BufferedWriter name='<stderr>'>
aquarius_1         | Call stack:
aquarius_1         |   File "/usr/local/bin/gunicorn", line 8, in <module>
aquarius_1         |     sys.exit(run())
aquarius_1         |   File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/wsgiapp.py", line 67, in run
aquarius_1         |     WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
aquarius_1         |   File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/base.py", line 231, in run
aquarius_1         |     super().run()
aquarius_1         |   File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/base.py", line 72, in run
aquarius_1         |     Arbiter(self).run()
aquarius_1         |   File "/usr/local/lib/python3.8/dist-packages/gunicorn/arbiter.py", line 209, in run
aquarius_1         |     self.sleep()
aquarius_1         |   File "/usr/local/lib/python3.8/dist-packages/gunicorn/arbiter.py", line 357, in sleep
aquarius_1         |     ready = select.select([self.PIPE[0]], [], [], 1.0)
aquarius_1         |   File "/usr/local/lib/python3.8/dist-packages/gunicorn/arbiter.py", line 242, in handle_chld
aquarius_1         |     self.reap_workers()
aquarius_1         |   File "/usr/local/lib/python3.8/dist-packages/gunicorn/arbiter.py", line 530, in reap_workers
aquarius_1         |     self.log.warning(
aquarius_1         |   File "/usr/local/lib/python3.8/dist-packages/gunicorn/glogging.py", line 261, in warning
aquarius_1         |     self.error_log.warning(msg, *args, **kwargs)
aquarius_1         |   File "/usr/lib/python3.8/logging/__init__.py", line 1445, in warning
aquarius_1         |     if self.isEnabledFor(WARNING):
aquarius_1         |   File "/usr/local/lib/python3.8/dist-packages/gunicorn/arbiter.py", line 242, in handle_chld
aquarius_1         |     self.reap_workers()
aquarius_1         |   File "/usr/local/lib/python3.8/dist-packages/gunicorn/arbiter.py", line 530, in reap_workers
aquarius_1         |     self.log.warning(
aquarius_1         |   File "/usr/local/lib/python3.8/dist-packages/gunicorn/glogging.py", line 261, in warning
aquarius_1         |     self.error_log.warning(msg, *args, **kwargs)
aquarius_1         |   File "/usr/lib/python3.8/logging/__init__.py", line 1446, in warning
aquarius_1         |     self._log(WARNING, msg, args, **kwargs)
aquarius_1         |   File "/usr/lib/python3.8/logging/__init__.py", line 1577, in _log
aquarius_1         |     self.handle(record)
aquarius_1         |   File "/usr/lib/python3.8/logging/__init__.py", line 1587, in handle
aquarius_1         |     self.callHandlers(record)
aquarius_1         |   File "/usr/lib/python3.8/logging/__init__.py", line 1649, in callHandlers
aquarius_1         |     hdlr.handle(record)
aquarius_1         |   File "/usr/lib/python3.8/logging/__init__.py", line 950, in handle
aquarius_1         |     self.emit(record)
aquarius_1         |   File "/usr/lib/python3.8/logging/__init__.py", line 1085, in emit
aquarius_1         |     self.flush()
aquarius_1         |   File "/usr/lib/python3.8/logging/__init__.py", line 1065, in flush
aquarius_1         |     self.stream.flush()
aquarius_1         |   File "/usr/local/lib/python3.8/dist-packages/gunicorn/arbiter.py", line 242, in handle_chld
aquarius_1         |     self.reap_workers()
aquarius_1         |   File "/usr/local/lib/python3.8/dist-packages/gunicorn/arbiter.py", line 530, in reap_workers
aquarius_1         |     self.log.warning(
aquarius_1         |   File "/usr/local/lib/python3.8/dist-packages/gunicorn/glogging.py", line 261, in warning
aquarius_1         |     self.error_log.warning(msg, *args, **kwargs)
aquarius_1         | Message: 'Worker with pid %s was terminated due to signal %s'
aquarius_1         | Arguments: (6054, 9)

**Comment by DMats** [comment]
@tmk1221 I was unable to reproduce the errors you've shown. I'm able to successfully create the asset, and it finishes rather quickly.

Work Console:
```pycon
>>> asset = ocean.assets.create(
...   metadata,
...   alice_wallet,
...   service_descriptors=[download_service],
...   data_token_address=token_address)
signing message with nonce 0: 0xDbec339392A8f8074506FDdfACCA0328bd022C15, account=0x66aB6D9362d4F35596279692F0251Db635165871
```

Barge console:
```docker
ganache_1          | eth_blockNumber
ganache_1          | eth_blockNumber
ganache_1          | eth_blockNumber
ganache_1          | eth_blockNumber
ganache_1          | eth_blockNumber
ganache_1          | eth_blockNumber
aquarius_1         | /usr/local/lib/python3.8/dist-packages/elasticsearch/connection/base.py:208: ElasticsearchWarning: [types removal] The parameter include_type_name should be explicitly specified in create index requests to prepare for 7.0. In 7.0 include_type_name will default to 'false', and requests are expected to omit the type name in mapping definitions.
aquarius_1         |   warnings.warn(message, category=ElasticsearchWarning)
aquarius_1         | 2021-07-19 19:20:27 695998f56170 root[102] INFO Schema: /usr/local/lib/python3.8/dist-packages/plecos/schemas/metadata_local_v0_5.json
provider_1         | default log level: 20, env var LOG_LEVEL INFO
provider_1         | Failed to load configuration file. Using default configs
provider_1         | default log level: 20, env var LOG_LEVEL INFO
provider_1         | Failed to load configuration file. Using default configs
provider_1         | 2021-07-19 19:20:27,290 - ocean_provider.utils.util - INFO - Connecting through Osmosis to generate the signed url.
provider_1         | 2021-07-19 19:20:27 4938676dc25d Osmosis[12] INFO Loading `on_premise` driver, url=https://raw.githubusercontent.com/trentmc/branin/master/branin.arff.
provider_1         | 2021-07-19 19:20:27 4938676dc25d Osmosis[12] INFO Loading `on_premise` driver, url=https://raw.githubusercontent.com/trentmc/branin/master/branin.arff.
provider_1         | 2021-07-19 19:20:27,327 - ocean_provider.utils.url - INFO - [i] Cannot get AAAA record for domain raw.githubusercontent.com: The DNS response does not contain an answer to the question: raw.githubusercontent.com. IN AAAA
provider_1         | 
ganache_1          | eth_newFilter
ganache_1          | eth_getFilterLogs
ganache_1          | eth_call
provider_1         | default log level: 20, env var LOG_LEVEL INFO
provider_1         | Failed to load configuration file. Using default configs
provider_1         | default log level: 20, env var LOG_LEVEL INFO
provider_1         | Failed to load configuration file. Using default configs
provider_1         | 2021-07-19 19:20:27,748 - ocean_provider.routes.consume - INFO - nonce for user 0x66aB6D9362d4F35596279692F0251Db635165871 is 0
provider_1         | 2021-07-19 19:20:27,902 - ocean_provider.routes.consume - INFO - encrypted urls 0x045f7338a3e4e9b214bf5fc3c500d6e4a29f19f96aa1afb697dfbd67f2948c8853845df4f9d227b7a415daafe62c8c1fe843d7a36f9c53c5a63a1e6c35f9c73b773d3b02fec2b20b96f2a7950bf9b0c32928179bce820d05d314ead4bde70f5bcd6ccfe5a0e5ecbf9326c41bfb7b3b07b1e26cc54d7f3246dba7e65cab6f16be2b8f2af227094d658ee91fd343530c79706e82455f9e3878cc738c0174e73c9d65272c60e8d29063f8e97580ccdd271768b7bfdd6aa4b70e357af3ee57d1ab04f98388ae298cd3c6d0540261af7a27d7c57b2a6a, publisher 0x66aB6D9362d4F35596279692F0251Db635165871, documentId 0xDbec339392A8f8074506FDdfACCA0328bd022C15
ganache_1          | eth_chainId
ganache_1          | eth_chainId
ganache_1          | eth_chainId
ganache_1          | eth_estimateGas
ganache_1          | eth_getTransactionCount
ganache_1          | eth_gasPrice
ganache_1          | eth_gasPrice
ganache_1          | eth_sendRawTransaction
ganache_1          | 
ganache_1          |   Transaction: 0x3ac3261acb3851d8e008c7cca510da1cc5f3e7eb6d588fb569aa8944557adc1e
ganache_1          |   Gas usage: 55826
ganache_1          |   Block Number: 18
ganache_1          |   Block Time: Mon Jul 19 2021 19:20:28 GMT+0000 (Coordinated Universal Time)
ganache_1          | 
ganache_1          | eth_getTransactionReceipt
ganache_1          | eth_getTransactionReceipt
ganache_1          | eth_getTransactionReceipt
ganache_1          | eth_blockNumber
aquarius_1         | 2021-07-19 19:20:29,077 - aquarius.events.events_monitor - DEBUG - Metadata monitor >>>> from_block:17, current_block:17 <<<<
aquarius_1         | 2021-07-19 19:20:29,077 - aquarius.events.events_monitor - DEBUG - get_event_logs (MetadataCreated, 17, 17)..
ganache_1          | eth_newFilter
ganache_1          | eth_getFilterLogs
aquarius_1         | 2021-07-19 19:20:29,095 - aquarius.events.events_monitor - DEBUG - get_event_logs (MetadataUpdated, 17, 17)..
ganache_1          | eth_newFilter
ganache_1          | eth_getFilterLogs
aquarius_1         | 2021-07-19 19:20:29,121 - aquarius.events.events_monitor - DEBUG - Metadata monitor >>>> from_block:17, current_block:18 <<<<
aquarius_1         | 2021-07-19 19:20:29,122 - aquarius.events.events_monitor - DEBUG - get_event_logs (MetadataCreated, 17, 18)..
ganache_1          | eth_newFilter
ganache_1          | eth_getFilterLogs
ganache_1          | eth_getBlockByNumber
aquarius_1         | 2021-07-19 19:20:29,157 - aquarius.events.events_monitor - INFO - Process new DDO, did from event log:did:op:Dbec339392A8f8074506FDdfACCA0328bd022C15, sender:0x66aB6D9362d4F35596279692F0251Db635165871
aquarius_1         | 2021-07-19 19:20:29,157 - aquarius.events.events_monitor - DEBUG - checking allowed publishers: 0x66aB6D9362d4F35596279692F0251Db635165871
aquarius_1         | 2021-07-19 19:20:29,161 - aquarius.events.events_monitor - INFO - Start processing MetadataCreated event: did=did:op:Dbec339392A8f8074506FDdfACCA0328bd022C15
aquarius_1         | 2021-07-19 19:20:29,161 - aquarius.events.events_monitor - DEBUG - block 18, contract: 0x9C2a015129969c98E9A5BcBEb61A5F907FF5b629, Sender: 0x66aB6D9362d4F35596279692F0251Db635165871 , txid: 0x3ac3261acb3851d8e008c7cca510da1cc5f3e7eb6d588fb569aa8944557adc1e
aquarius_1         | 2021-07-19 19:20:29,161 - aquarius.events.events_monitor - DEBUG - decoding with did did:op:Dbec339392A8f8074506FDdfACCA0328bd022C15 and flags b'\x01'
aquarius_1         | 2021-07-19 19:20:29,161 - aquarius.events.events_monitor - DEBUG - flags: b'\x01'
aquarius_1         | 2021-07-19 19:20:29,161 - aquarius.events.events_monitor - DEBUG - checkflags: 1
aquarius_1         | 2021-07-19 19:20:29,162 - aquarius.events.events_monitor - DEBUG - Decompressed to b'{"@context": "https://w3id.org/did/v1", "id": "did:op:Dbec339392A8f8074506FDdfACCA0328bd022C15", "created": "2021-07-19T19:20:27Z", "publicKey": [{"id": "did:op:Dbec339392A8f8074506FDdfACCA0328bd022C15", "type": "EthereumECDSAKey", "owner": "0x66aB6D9362d4F35596279692F0251Db635165871"}], "authentication": [{"type": "RsaSignatureAuthentication2018", "publicKey": "did:op:Dbec339392A8f8074506FDdfACCA0328bd022C15"}], "service": [{"type": "metadata", "attributes": {"main": {"type": "dataset", "name": "branin", "author": "Trent", "license": "CC0: Public Domain", "dateCreated": "2019-12-28T10:55:11Z", "files": [{"index": 0, "contentType": "text/text"}]}, "encryptedFiles": "0x045f7338a3e4e9b214bf5fc3c500d6e4a29f19f96aa1afb697dfbd67f2948c8853845df4f9d227b7a415daafe62c8c1fe843d7a36f9c53c5a63a1e6c35f9c73b773d3b02fec2b20b96f2a7950bf9b0c32928179bce820d05d314ead4bde70f5bcd6ccfe5a0e5ecbf9326c41bfb7b3b07b1e26cc54d7f3246dba7e65cab6f16be2b8f2af227094d658ee91fd343530c79706e82455f9e3878cc738c0174e73c9d65272c60e8d29063f8e97580ccdd271768b7bfdd6aa4b70e357af3ee57d1ab04f98388ae298cd3c6d0540261af7a27d7c57b2a6a"}, "serviceEndpoint": "http://localhost:5000/api/v1/aquarius/assets/ddo/did:op:Dbec339392A8f8074506FDdfACCA0328bd022C15", "index": 0}, {"type": "access", "attributes": {"main": {"name": "dataAssetAccessServiceAgreement", "creator": "0x66aB6D9362d4F35596279692F0251Db635165871", "timeout": 86400, "datePublished": "2019-12-28T10:55:11Z", "cost": 1.0}}, "serviceEndpoint": "http://localhost:8030", "index": 3}], "proof": {"type": "DDOIntegritySignature", "created": "2021-07-19T19:20:27Z", "creator": "0x66aB6D9362d4F35596279692F0251Db635165871", "signatureValue": "0x77c71f00435132851329a3014b4eed4a6463b2ed1d1a3d916094ca2cf53b29a0293a543de137e5e12a07b354e621777e5ebb529179ba1b8592ec94f6a7537fc01b", "checksum": {"0": "35acddb05beca093f3eb991099f55de7482726b8b38e96225f04d6347c368fb8", "3": "a7b08afd86967bd5cd6f09d338a5804e11003ccc35041025fafae8ef50b6e7ab"}}, "dataToken": "0xDbec339392A8f8074506FDdfACCA0328bd022C15"}'
aquarius_1         | 2021-07-19 19:20:29,162 - aquarius.events.events_monitor - DEBUG - After unpack rawddo:b'{"@context": "https://w3id.org/did/v1", "id": "did:op:Dbec339392A8f8074506FDdfACCA0328bd022C15", "created": "2021-07-19T19:20:27Z", "publicKey": [{"id": "did:op:Dbec339392A8f8074506FDdfACCA0328bd022C15", "type": "EthereumECDSAKey", "owner": "0x66aB6D9362d4F35596279692F0251Db635165871"}], "authentication": [{"type": "RsaSignatureAuthentication2018", "publicKey": "did:op:Dbec339392A8f8074506FDdfACCA0328bd022C15"}], "service": [{"type": "metadata", "attributes": {"main": {"type": "dataset", "name": "branin", "author": "Trent", "license": "CC0: Public Domain", "dateCreated": "2019-12-28T10:55:11Z", "files": [{"index": 0, "contentType": "text/text"}]}, "encryptedFiles": "0x045f7338a3e4e9b214bf5fc3c500d6e4a29f19f96aa1afb697dfbd67f2948c8853845df4f9d227b7a415daafe62c8c1fe843d7a36f9c53c5a63a1e6c35f9c73b773d3b02fec2b20b96f2a7950bf9b0c32928179bce820d05d314ead4bde70f5bcd6ccfe5a0e5ecbf9326c41bfb7b3b07b1e26cc54d7f3246dba7e65cab6f16be2b8f2af227094d658ee91fd343530c79706e82455f9e3878cc738c0174e73c9d65272c60e8d29063f8e97580ccdd271768b7bfdd6aa4b70e357af3ee57d1ab04f98388ae298cd3c6d0540261af7a27d7c57b2a6a"}, "serviceEndpoint": "http://localhost:5000/api/v1/aquarius/assets/ddo/did:op:Dbec339392A8f8074506FDdfACCA0328bd022C15", "index": 0}, {"type": "access", "attributes": {"main": {"name": "dataAssetAccessServiceAgreement", "creator": "0x66aB6D9362d4F35596279692F0251Db635165871", "timeout": 86400, "datePublished": "2019-12-28T10:55:11Z", "cost": 1.0}}, "serviceEndpoint": "http://localhost:8030", "index": 3}], "proof": {"type": "DDOIntegritySignature", "created": "2021-07-19T19:20:27Z", "creator": "0x66aB6D9362d4F35596279692F0251Db635165871", "signatureValue": "0x77c71f00435132851329a3014b4eed4a6463b2ed1d1a3d916094ca2cf53b29a0293a543de137e5e12a07b354e621777e5ebb529179ba1b8592ec94f6a7537fc01b", "checksum": {"0": "35acddb05beca093f3eb991099f55de7482726b8b38e96225f04d6347c368fb8", "3": "a7b08afd86967bd5cd6f09d338a5804e11003ccc35041025fafae8ef50b6e7ab"}}, "dataToken": "0xDbec339392A8f8074506FDdfACCA0328bd022C15"}'
aquarius_1         | 2021-07-19 19:20:29,162 - aquarius - INFO - got event MetadataCreated request: {'@context': 'https://w3id.org/did/v1', 'id': 'did:op:Dbec339392A8f8074506FDdfACCA0328bd022C15', 'created': '2021-07-19T19:20:27Z', 'publicKey': [{'id': 'did:op:Dbec339392A8f8074506FDdfACCA0328bd022C15', 'type': 'EthereumECDSAKey', 'owner': '0x66aB6D9362d4F35596279692F0251Db635165871'}], 'authentication': [{'type': 'RsaSignatureAuthentication2018', 'publicKey': 'did:op:Dbec339392A8f8074506FDdfACCA0328bd022C15'}], 'service': [{'type': 'metadata', 'attributes': {'main': {'type': 'dataset', 'name': 'branin', 'author': 'Trent', 'license': 'CC0: Public Domain', 'dateCreated': '2019-12-28T10:55:11Z', 'files': [{'index': 0, 'contentType': 'text/text'}]}, 'encryptedFiles': '0x045f7338a3e4e9b214bf5fc3c500d6e4a29f19f96aa1afb697dfbd67f2948c8853845df4f9d227b7a415daafe62c8c1fe843d7a36f9c53c5a63a1e6c35f9c73b773d3b02fec2b20b96f2a7950bf9b0c32928179bce820d05d314ead4bde70f5bcd6ccfe5a0e5ecbf9326c41bfb7b3b07b1e26cc54d7f3246dba7e65cab6f16be2b8f2af227094d658ee91fd343530c79706e82455f9e3878cc738c0174e73c9d65272c60e8d29063f8e97580ccdd271768b7bfdd6aa4b70e357af3ee57d1ab04f98388ae298cd3c6d0540261af7a27d7c57b2a6a'}, 'serviceEndpoint': 'http://localhost:5000/api/v1/aquarius/assets/ddo/did:op:Dbec339392A8f8074506FDdfACCA0328bd022C15', 'index': 0}, {'type': 'access', 'attributes': {'main': {'name': 'dataAssetAccessServiceAgreement', 'creator': '0x66aB6D9362d4F35596279692F0251Db635165871', 'timeout': 86400, 'datePublished': '2019-12-28T10:55:11Z', 'cost': 1.0}}, 'serviceEndpoint': 'http://localhost:8030', 'index': 3}], 'proof': {'type': 'DDOIntegritySignature', 'created': '2021-07-19T19:20:27Z', 'creator': '0x66aB6D9362d4F35596279692F0251Db635165871', 'signatureValue': '0x77c71f00435132851329a3014b4eed4a6463b2ed1d1a3d916094ca2cf53b29a0293a543de137e5e12a07b354e621777e5ebb529179ba1b8592ec94f6a7537fc01b', 'checksum': {'0': '35acddb05beca093f3eb991099f55de7482726b8b38e96225f04d6347c368fb8', '3': 'a7b08afd86967bd5cd6f09d338a5804e11003ccc35041025fafae8ef50b6e7ab'}}, 'dataToken': '0xDbec339392A8f8074506FDdfACCA0328bd022C15'}
ganache_1          | eth_call
ganache_1          | eth_call
ganache_1          | eth_call
ganache_1          | eth_call
ganache_1          | eth_call
ganache_1          | eth_call
ganache_1          | eth_call
aquarius_1         | 2021-07-19 19:20:29 695998f56170 root[25] INFO Schema: /usr/local/lib/python3.8/dist-packages/plecos/schemas/metadata_remote_v0_5.json
elasticsearch_1    | [2021-07-19T19:20:29,427][INFO ][o.e.c.m.MetaDataMappingService] [-rw1UH1] [aquarius/5m7pX12CTo-XZEia-2C_sw] update_mapping [_doc]
aquarius_1         | 2021-07-19 19:20:30,225 - aquarius.events.events_monitor - DEBUG - DDO saved: did=did:op:Dbec339392A8f8074506FDdfACCA0328bd022C15, name=branin, publisher=0x66aB6D9362d4F35596279692F0251Db635165871
aquarius_1         | 2021-07-19 19:20:30,225 - aquarius.events.events_monitor - INFO - Done processing MetadataCreated event: did=did:op:Dbec339392A8f8074506FDdfACCA0328bd022C15. DDO SAVED TO DB
aquarius_1         | 2021-07-19 19:20:30,226 - aquarius.events.events_monitor - DEBUG - get_event_logs (MetadataUpdated, 17, 18)..
ganache_1          | eth_newFilter
ganache_1          | eth_getFilterLogs
ganache_1          | eth_blockNumber
aquarius_1         | 2021-07-19 19:20:30,902 - aquarius.events.metadata_updater - DEBUG - Price/Liquidity monitor >>>> from_block:17, current_block:17 <<<<
ganache_1          | eth_getLogs
ganache_1          | eth_getLogs
ganache_1          | eth_getLogs
aquarius_1         | 2021-07-19 19:20:30,923 - aquarius.events.metadata_updater - DEBUG - Got pools: []
ganache_1          | eth_getLogs
ganache_1          | eth_getLogs
aquarius_1         | 2021-07-19 19:20:30,938 - aquarius.events.metadata_updater - DEBUG - Got dt/exchanges: []
aquarius_1         | 2021-07-19 19:20:30,945 - aquarius.events.metadata_updater - DEBUG - Price/Liquidity monitor >>>> from_block:17, current_block:18 <<<<
ganache_1          | eth_getLogs
ganache_1          | eth_getLogs
ganache_1          | eth_getLogs
aquarius_1         | 2021-07-19 19:20:30,970 - aquarius.events.metadata_updater - DEBUG - Got pools: []
ganache_1          | eth_getLogs
ganache_1          | eth_getLogs
aquarius_1         | 2021-07-19 19:20:30,988 - aquarius.events.metadata_updater - DEBUG - Got dt/exchanges: []
ganache_1          | eth_blockNumber
ganache_1          | eth_blockNumber
ganache_1          | eth_blockNumber
ganache_1          | eth_blockNumber
ganache_1          | eth_blockNumber
ganache_1          | eth_blockNumber
ganache_1          | eth_blockNumber
```

I can see from the `Terminal.txt` you posted that you're on a Mac.  Did you increase the docker memory to 4GB instead of 2 before running barge? See for details https://github.com/oceanprotocol/barge#prerequisites 

Also, it might be worth trying to prune your docker images before running barge.

```console
docker system prune -a --volumes
```

**Comment by calina-c** [comment]
@tmk1221 any news? Were you successful with David's recommendations?

**Comment by calina-c** [comment]
I am closing this due to inactivity.
